### ISSUE TITLE
Issue In Windows

### ISSUE THREAD

**Issue by bfuzail** [arkisoul/whatsapp-bulk-message-automation#1]
Traceback (most recent call last):
  File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 34, in start_process
    self.load_driver()
  File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 48, in load_driver
    self.driver = webdriver.Chrome(executable_path=r'C:\Users\Nityam\AppData\Local\Programs\Python\Python39\chromedriver.exe',
TypeError: __init__() got an unexpected keyword argument 'options'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 142, in <module>
    whatsapp.start_process()
  File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 37, in start_process
    self.close_driver()
  File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 130, in close_driver
    self.driver.quit()
AttributeError: 'NoneType' object has no attribute 'quit'

**Comment by arpitjainio** [comment]
> Traceback (most recent call last):
> File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 34, in start_process
> self.load_driver()
> File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 48, in load_driver
> self.driver = webdriver.Chrome(executable_path=r'C:\Users\Nityam\AppData\Local\Programs\Python\Python39\chromedriver.exe',
> TypeError: **init**() got an unexpected keyword argument 'options'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 142, in 
> whatsapp.start_process()
> File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 37, in start_process
> self.close_driver()
> File "d:\whatsapp-bulk-message-automation-main\app\app.py", line 130, in close_driver
> self.driver.quit()
> AttributeError: 'NoneType' object has no attribute 'quit'

@bfuzail 

Do you have chromedriver installed on your system? Make sure to set its path in system PATH.
Here, is how you achieve it.
- Article: https://www.computerhope.com/issues/ch000549.htm
- Video: https://www.youtube.com/watch?v=dz59GsdvUF8

Once the path is successfully set in system PATH. You can change the below line of code
Existing code : self.driver = webdriver.Chrome(executable_path=r'C:\Users\Nityam\AppData\Local\Programs\Python\Python39\chromedriver.exe',
Replace it with: self.driver = webdriver.Chrome()

If after above change the script doesn't work. Try putting executable_path of your chromedriver.

Hope this helps.

**Comment by arpitjainio** [comment]
Closing the issue due to long time inactivity.
