### ISSUE TITLE
Geeting Error During Script Run

### ISSUE THREAD

**Issue by Savaimaheshwari** [arkisoul/whatsapp-bulk-message-automation#2]
![WhatsApp Image 2021-10-05 at 1 12 11 PM](https://user-images.githubusercontent.com/20859949/136014899-4ccf67e7-fd16-4cd0-8135-e99178fd11ad.jpeg)

**Comment by arpitjainio** [comment]
It may be related to chrome driver executable path. I explained how to do it [here in #1 ](https://github.com/arkisoul/whatsapp-bulk-message-automation/issues/1#issuecomment-912285397)

**Comment by arpitjainio** [comment]
Closing the issue due to long time inactivity.
