### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by grace764** [arkisoul/whatsapp-bulk-message-automation#3]
Is this still working and any video guide / tutorial to use this

**Comment by arpitjainio** [comment]
The README file explains how to use this automation script. Let me know if you face any blockers.

**Comment by arpitjainio** [comment]
did it work for you @grace764?

**Comment by arpitjainio** [comment]
@grace764 the repo is updated. It should work not if it wasn't working earlier for you. Open a new issue if you face any challenges.
